---

- name: "Ensure Go is installed"
  shell: |
    if ! command -v go &>/dev/null; then
      sudo apt install golang-go -y
    else
      echo "Go is already installed"
    fi
  args:
    executable: /bin/bash
  register: go_installation_result
  changed_when: "'Go is already installed' not in go_installation_result.stdout"
  tags: install

- name: "Update Go"
  shell: |
    cd ~/Tools/
    if [ ! -d update-golang ]; then
      git clone https://github.com/udhos/update-golang
      cd update-golang
      sudo ./update-golang.sh
    else
      echo "update-golang folder already exists"
    fi
  args:
    executable: /bin/bash
  register: go_update_result
  changed_when: "'update-golang folder already exists' not in go_update_result.stdout"
  tags: update

- name: "Install Go tools"
  shell: "GO111MODULE=on go install {{ item.value }}"
  environment:
    GOPATH: "/usr/local/go"           # Adjust to your GOPATH if necessary
    GOBIN: "/usr/local/go/bin"        # This ensures the installed tools will be placed here
  with_dict:
    subfinder: "github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest"
    assetfinder: "github.com/tomnomnom/assetfinder@latest"
    amass: "github.com/OWASP/Amass/v3/...@master"
    anew: "github.com/tomnomnom/anew@latest"
    httpx: "github.com/projectdiscovery/httpx/cmd/httpx@latest"
    katana: "github.com/projectdiscovery/katana/cmd/katana@latest"
    gf: "github.com/tomnomnom/gf@latest"
    gau: "github.com/lc/gau/v2/cmd/gau@latest"
    qsreplace: "github.com/tomnomnom/qsreplace@latest"
    jsubfinder: "github.com/ThreatUnkown/jsubfinder@latest"
    dalfox: "github.com/hahwul/dalfox/v2@latest"
    ffuf: "github.com/ffuf/ffuf@latest"
    naabu: "github.com/projectdiscovery/naabu/v2/cmd/naabu@latest"
    nuclei: "github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest"
    cent: "github.com/xm1k3/cent@latest"
