---
- name: "Customizing Ubuntu"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/install-tools"
    - role: "roles/configure-tmux"
    - role: "roles/configure-zap"
    - role: "roles/configure-postman"
    - role: "roles/customize-terminal"
    - role: "roles/customize-browser"
    - role: "roles/configure-logging"
    - role: "roles/customize-burp"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}" 
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - DEVSENSE.phptools-vscode
            - GitHub.copilot
            - snyk-security.snyk-vulnerability-scanner

